from collections.abc import Iterable
from pathlib import Path
from typing import Protocol

from customer_data_product.domain.models import BatchFile


class ObjectStorage(Protocol):
    def put(self, key: str, source: Iterable[bytes]) -> int: ...

    def get(self, key: str) -> Path: ...

    def list(self, prefix: str) -> list[str]: ...

    def size(self, key: str) -> int: ...


class EventPublisher(Protocol):
    def publish(self, batch_id: str) -> None: ...


class BatchRepository(Protocol):
    def create_batch(self, batch_id: str, source: str) -> None: ...

    def get_batch(self, batch_id: str) -> dict[str, object] | None: ...

    def update_status(self, batch_id: str, status: str, **counts: object) -> None: ...

    def add_file(self, batch_file: BatchFile) -> None: ...

    def list_files(self, batch_id: str) -> list[BatchFile]: ...

    def publish_customer_snapshot(self, batch_id: str) -> int: ...


class DataProcessor(Protocol):
    def process_batch(
        self, batch_id: str
    ) -> dict[str, object]: ...
